// services/WorkflowArtifactBuilder.js
// Pure function that builds a readable markdown document from workflow execution data.

/**
 * Format a duration in milliseconds to a human-readable string.
 * @param {number|null|undefined} ms
 * @returns {string}
 */
function formatDuration(ms) {
  if (ms == null || !Number.isFinite(ms) || ms < 0) return 'N/A';
  const totalSeconds = Math.floor(ms / 1000);
  if (ms < 60_000) return `${totalSeconds}s`;
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  if (ms < 3_600_000) return `${minutes}m ${seconds}s`;
  return `${hours}h ${minutes}m ${seconds}s`;
}

/**
 * Sort agent entries by firstMessageAt (temporal execution order).
 * Null/undefined timestamps sort last.
 * @param {Array<[string, object]>} entries
 * @returns {Array<[string, object]>}
 */
function sortAgentEntries(entries) {
  return entries.sort(([, a], [, b]) => {
    const aTime = a.firstMessageAt;
    const bTime = b.firstMessageAt;
    if (aTime == null && bTime == null) return 0;
    if (aTime == null) return 1;
    if (bTime == null) return -1;
    return new Date(aTime).getTime() - new Date(bTime).getTime();
  });
}

/**
 * Build a markdown artifact from workflow execution data.
 *
 * @param {object} params
 * @param {string} params.workflowName
 * @param {string} [params.workflowDescription]
 * @param {string} params.executionId
 * @param {string} params.status
 * @param {string} [params.startedAt]
 * @param {string} [params.endedAt]
 * @param {number} [params.durationMs]
 * @param {object} [params.agentOutputs] - keyed by nodeId
 * @returns {string} Markdown document
 */
export function buildWorkflowArtifact({
  workflowName = 'Untitled Workflow',
  workflowDescription,
  executionId = 'unknown',
  status = 'unknown',
  startedAt,
  endedAt,
  durationMs,
  agentOutputs,
} = {}) {
  const lines = [];

  // Header
  lines.push(`# Workflow: ${workflowName}`);
  if (workflowDescription) {
    lines.push(`> ${workflowDescription}`);
  }
  lines.push('');
  lines.push(
    `**Execution:** \`${executionId}\` · **Status:** ${status} · **Duration:** ${formatDuration(durationMs)}`
  );
  lines.push(
    `**Started:** ${startedAt || 'N/A'} · **Ended:** ${endedAt || 'N/A'}`
  );
  lines.push('');
  lines.push('---');

  // Agent sections
  const entries = agentOutputs && typeof agentOutputs === 'object'
    ? Object.entries(agentOutputs)
    : [];

  if (entries.length === 0) {
    lines.push('');
    lines.push('No agent outputs were captured for this execution.');
  } else {
    const sorted = sortAgentEntries(entries);
    for (const [nodeId, agent] of sorted) {
      const label = agent.label || nodeId;
      const provider = agent.provider || 'N/A';
      const agentStatus = agent.status || 'unknown';
      const messageCount = agent.messageCount ?? 0;
      const finalText = agent.finalText || '(No output captured)';
      const handoffs = Array.isArray(agent.handoffPayloads) ? agent.handoffPayloads : [];

      lines.push('');
      lines.push(`## ${label} (\`${nodeId}\`)`);
      lines.push(
        `**Provider:** ${provider} · **Status:** ${agentStatus} · **Messages:** ${messageCount}`
      );
      lines.push('');
      lines.push(finalText);

      for (const handoff of handoffs) {
        const target = handoff.target || 'unknown';
        const payload = handoff.payload != null ? handoff.payload : {};
        lines.push('');
        lines.push(`### Handoff → ${target}`);
        lines.push('```json');
        lines.push(JSON.stringify(payload, null, 2));
        lines.push('```');
      }

      lines.push('');
      lines.push('---');
    }
  }

  // Footer
  lines.push('');
  lines.push(`*Generated by Claude Code Visual Manager · ${new Date().toISOString()}*`);

  return lines.join('\n');
}
